/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package comparable;

public class Main {

    public static void main(String[] args) {

        XmlReader myXmlReader = new XmlReader("customers.xml");

        Customer[] myCustomers = myXmlReader.getCustomers();

        // Uncomment when you are ready to test your program

        // System.out.println(myCustomers.length);

        // Compare the first and second customers
        // System.out.println("C0 COMPARETO C1:" +  myCustomers[0].compareTo(myCustomers[1]));

        // Compare the second and third customers
        // System.out.println("C1 COMPARETO C2:" +  myCustomers[1].compareTo(myCustomers[2]));
    }
}
